name = "testing"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "103.133.223.50-2096"
UUID = "7d9b9ddb-12c8-416a-adf9-94386a8bd209"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
